import = [ "~/.config/alacritty/themes/everforest_light" ]

[window]

opacity = 0.8  

dimensions = { columns = 120, lines = 30}

padding = { x = 20, y = 10}

[font]

normal = { family = "Hack", style = "Regular" }

bold = { family = "Hack", style = "Bold" }

italic = { family = "Hack", style = "Italic" }

bold_italic = { family = "Hack", style = "Bold Italic" }

size = 13

[cursor]

style = { shape = "Block", blinking = "On"}

# style.blinking = "On"
