" Vim Plugin
call plug#begin('~/.vim/plugged')
Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'Yggdroot/indentLine'
Plug 'luochen1990/rainbow'
call plug#end() 

" 键位绑定
let mapleader = ";"
nnoremap <Leader>q :q<CR>
nnoremap <Leader>w :w<CR>
nnoremap <Leader>g :NERDTreeToggle<CR>
nnoremap <Leader>f :NERDTreeFind<CR>

set clipboard=unnamedplus   " 使用系统剪切版 -> Vim
set relativenumber " 设置显示相对行号
set wildmenu " 命令预览 
set tabstop=4        " 一个 tab 显示为 4 个空格宽度
set shiftwidth=4     " 每次自动缩进时使用 4 个空格

highlight Pmenu ctermbg=black ctermfg=white guibg=black guifg=white
highlight PmenuSel ctermbg=grey ctermfg=black guibg=grey guifg=black
highlight CocErrorLine cterm=undercurl ctermfg=Red " 将错误提醒改为 红线
" 允许回车键在自动补全菜单中确认选择
inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm() : "\<CR>"
" 使用 Tab 键选择补全项，Shift-Tab 反向选择
inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <silent><expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<C-h>"
