#!/bin/bash

# 获取当前音量信息
volume_info=$(amixer get Master | grep -oP '\[([0-9]+%)\]' | head -1)

# 获取静音状态
mute_status=$(amixer get Master | grep '\[off\]')

# 检查是否静音
if [ -n "$mute_status" ]; then
    echo "MUTE"
else
    # 输出当前音量
    echo $volume_info | tr -d '[]'
fi

